swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Courses API
  # put the contact info for your development or API team
  contact:
    email: alexander@makklays.com.ua

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: front-end
  description: Operations available for front-end developers

paths:
  /courses:
    get:
      tags:
      - front-end
      summary: searches course
      operationId: searchCourse
      description: |
        By passing in the appropriate options, you can search for
        available course in the system or all courses by 100
      produces:
      - application/json
      parameters:
      - in: query
        name: page
        description: number of page 
        required: false
        type: integer
      - in: query
        name: send_currency
        description: number of currency
        type: integer
        format: int32
        minimum: 0
      - in: query
        name: revice_currency
        description: number of currency 
        type: integer
        format: int32
        minimum: 0
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'
        201:
          description: item created
        400:
          description: bad input parameter
        401:
          description: don't have Bearer token 
        409:
          description: an existing item already exists 
        422:
          description: invalid validation 
        500:
          description: exception 
    post:
      tags:
      - admins
      summary: adds an course item
      operationId: addCourse
      description: Adds an item to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: course
        description: Item of course to add
        schema:
          $ref: '#/definitions/Course'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        401:
          description: don't have Bearer token 
        409:
          description: an existing item already exists 
        422:
          description: invalid validation 
        500:
          description: exception 
definitions:
  Course:
    type: object
    required:
    - id
    - send_currency
    - recive_currency
    - send_course
    - recive_course
    properties:
      id:
        type: integer
        format: id
        example: 1234567
      send_currency:
        type: integer
        format: send_currency
        example: 212
      recive_currency:
        type: integer
        format: recive_currency
        example: 12
      send_course:
        type: string
        example: 123.12121212
      recive_course:
        type: string
        example: 1
      created_at:
        type: string
        format: date-time
        example: "2021-12-15 09:12:33.00"
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Makklays/Currencies/1.0.0
schemes:
 - https
